### ISSUE TITLE
uvisor header files should include headers on which they depend.

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/uvisor-lib#24]
For example, "uvisor-lib/interrupts.h" depends on "uvisor-lib/uvisor_exports.h" but does not include it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1859

**Comment by bremoran** [comment]
Two other solutions:

* place a warning in each non-primary header file that checks whether a primary header has been included
* move all non-primary headers into a detail directory.

Any of these would solve a common workflow problem:

* User looks up required API in documentation.
* User finds header that defines required API.
* User includes only that header
* API doesn't have required definitions and breaks.

**Comment by AlessandroA** [comment]
Fixed in:
d8aaec4 Update uvisor-lib.h to latest header files
fb889b1 Add missing inclusions in unsupported.h
6c031a6 Replace API header files with redirections to uVisor
ARMmbed/uvisor@7b783f3 Fix header file inclusion

Please note that now including a "secondary" uvisor-lib header file is deprecated. The recommended behavior is to include `uvisor-lib/uvisor-lib.h` only, which in turn includes all secondary ones. You can still include a secondary header file for the time being, but this possibility will be removed in a later version.

That being said, the commits above made the secondary header files self-contained anyway, as suggested by this issue.
